version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrentvpn_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: binhex/arch-qbittorrentvpn:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - VPN_ENABLED=no
      - VPN_USER=YOUR_NORD_USERNAME
      - VPN_PASS=YOUR_NORD_PASSWORD
      - VPN_PROV=nordvpn
      - VPN_CLIENT=wireguard
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
